print("Desculpe. Um erro interno foi encontrado ao Ãºltilizar esse comando!")
